  - name: Download Wordpress Source
    async: 500
    poll: 0
    register: wp_source_result
    get_url:
      url: "{{ wp['url'] }}"
      checksum: "{{ wp['sha1'] }}"
      dest: "{{ wp['source'] }}"

  - name: Install Apache2 Package and Change Service port for Debian
    import_tasks: Debian/WP_Debian.yaml
    when: ansible_facts['os_family'] == "Debian"

  - name: Install Httpd Package Change Service port for RedHat
    import_tasks: RedHat/WP_RedHat.yaml
    when: ansible_facts['os_family'] == "RedHat"

  - name: sync
    async_status:
      jid: "{{ wp_source_result.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100
    delay: 5

  - name: Unarchive Wordpress Source
    unarchive:
      src: "{{ wp['source'] }}"
      remote_src: true
      dest: /var/www/html

  - name: Setting Wordpress Database Configuration
    template:
      src: wp-config.php.j2
      dest: "{{ wp['config_path'] }}"

